# Generated by Django 4.0.3 on 2022-05-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='page_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
    ]
