# Generated by Django 4.0.3 on 2022-06-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescriptionimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdescriptionimages', to='shop.product'),
        ),
    ]
